//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34209
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 原始文件名:
// 生成日期: 2016/5/26 15:20:14
namespace WAPWrapper.SPFGallery
{
    
    /// <summary>
    /// 架构中不存在 GalleryDataProvider 的注释。
    /// </summary>
    public partial class GalleryDataProvider : global::System.Data.Services.Client.DataServiceContext
    {
        /// <summary>
        /// 初始化新的 GalleryDataProvider 对象。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public GalleryDataProvider(global::System.Uri serviceRoot) : 
                base(serviceRoot, global::System.Data.Services.Common.DataServiceProtocolVersion.V3)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.UrlConventions = global::System.Data.Services.Common.DataServiceUrlConventions.KeyAsSegment;
            this.OnContextCreated();
            this.Format.LoadServiceModel = GeneratedEdmModel.GetInstance;
        }
        partial void OnContextCreated();
        /// <summary>
        /// 因为在 Visual Studio 中为此服务引用配置的
        /// 命名空间与在服务器架构中指示的命名空间不同，所以
        /// 使用类型映射器在这两者之间进行映射。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            global::System.Type resolvedType = this.DefaultResolveType(typeName, "MicrosoftCompute", "WAPWrapper.SPFGallery");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            return null;
        }
        /// <summary>
        /// 因为在 Visual Studio 中为此服务引用配置的
        /// 命名空间与在服务器架构中指示的命名空间不同，所以
        /// 使用类型映射器在这两者之间进行映射。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            if (clientType.Namespace.Equals("WAPWrapper.SPFGallery", global::System.StringComparison.Ordinal))
            {
                return string.Concat("MicrosoftCompute.", clientType.Name);
            }
            return clientType.FullName;
        }
        /// <summary>
        /// 架构中不存在 GalleryItems 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<GalleryItem> GalleryItems
        {
            get
            {
                if ((this._GalleryItems == null))
                {
                    this._GalleryItems = base.CreateQuery<GalleryItem>("GalleryItems");
                }
                return this._GalleryItems;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<GalleryItem> _GalleryItems;
        /// <summary>
        /// 架构中不存在 GalleryPackageContentFiles 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<GalleryPackageContentFile> GalleryPackageContentFiles
        {
            get
            {
                if ((this._GalleryPackageContentFiles == null))
                {
                    this._GalleryPackageContentFiles = base.CreateQuery<GalleryPackageContentFile>("GalleryPackageContentFiles");
                }
                return this._GalleryPackageContentFiles;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<GalleryPackageContentFile> _GalleryPackageContentFiles;
        /// <summary>
        /// 架构中不存在 ViewDefinitions 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<ViewDefinition> ViewDefinitions
        {
            get
            {
                if ((this._ViewDefinitions == null))
                {
                    this._ViewDefinitions = base.CreateQuery<ViewDefinition>("ViewDefinitions");
                }
                return this._ViewDefinitions;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<ViewDefinition> _ViewDefinitions;
        /// <summary>
        /// 架构中不存在 GalleryItems 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToGalleryItems(GalleryItem galleryItem)
        {
            base.AddObject("GalleryItems", galleryItem);
        }
        /// <summary>
        /// 架构中不存在 GalleryPackageContentFiles 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToGalleryPackageContentFiles(GalleryPackageContentFile galleryPackageContentFile)
        {
            base.AddObject("GalleryPackageContentFiles", galleryPackageContentFile);
        }
        /// <summary>
        /// 架构中不存在 ViewDefinitions 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToViewDefinitions(ViewDefinition viewDefinition)
        {
            base.AddObject("ViewDefinitions", viewDefinition);
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private abstract class GeneratedEdmModel
        {
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::Microsoft.Data.Edm.IEdmModel ParsedModel = LoadModelFromString();
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private const string ModelPart0 = "<edmx:Edmx Version=\"1.0\" xmlns:edmx=\"http://schemas.microsoft.com/ado/2007/06/edm" +
                "x\"><edmx:DataServices m:DataServiceVersion=\"3.0\" m:MaxDataServiceVersion=\"3.0\" x" +
                "mlns:m=\"http://schemas.microsoft.com/ado/2007/08/dataservices/metadata\"><Schema " +
                "Namespace=\"MicrosoftCompute\" xmlns=\"http://schemas.microsoft.com/ado/2009/11/edm" +
                "\"><EntityType Name=\"NamedVersionedPublishedEntity\" Abstract=\"true\"><Key><Propert" +
                "yRef Name=\"Name\" /><PropertyRef Name=\"Publisher\" /><PropertyRef Name=\"Version\" /" +
                "></Key><Property Name=\"Name\" Type=\"Edm.String\" Nullable=\"false\" /><Property Name" +
                "=\"Publisher\" Type=\"Edm.String\" Nullable=\"false\" /><Property Name=\"Version\" Type=" +
                "\"Edm.String\" Nullable=\"false\" /></EntityType><EntityType Name=\"GalleryItem\" Base" +
                "Type=\"MicrosoftCompute.NamedVersionedPublishedEntity\" Abstract=\"true\"><Property " +
                "Name=\"ContentUrl\" Type=\"Edm.String\" /><Property Name=\"Description\" Type=\"Edm.Str" +
                "ing\" /><Property Name=\"IconUrl\" Type=\"Edm.String\" /><Property Name=\"Label\" Type=" +
                "\"Edm.String\" /><Property Name=\"PublishDate\" Type=\"Edm.DateTime\" /><Property Name" +
                "=\"PublisherLabel\" Type=\"Edm.String\" /><NavigationProperty Name=\"Content\" Relatio" +
                "nship=\"MicrosoftCompute.GalleryItem_Content\" ToRole=\"Content\" FromRole=\"GalleryI" +
                "tem\" /></EntityType><EntityType Name=\"ResourceDefinitionGalleryItem\" BaseType=\"M" +
                "icrosoftCompute.GalleryItem\" Abstract=\"true\"><Property Name=\"ResourceDefinition\"" +
                " Type=\"Edm.Stream\" Nullable=\"false\" /><Property Name=\"ResourceDefinitionUrl\" Typ" +
                "e=\"Edm.String\" /><Property Name=\"ViewDefinitionUrl\" Type=\"Edm.String\" /></Entity" +
                "Type><EntityType Name=\"VMRoleGalleryItem\" BaseType=\"MicrosoftCompute.ResourceDef" +
                "initionGalleryItem\" /><EntityType Name=\"GalleryPackageContentFile\" m:HasStream=\"" +
                "true\"><Key><PropertyRef Name=\"Name\" /><PropertyRef Name=\"Publisher\" /><PropertyR" +
                "ef Name=\"Version\" /><PropertyRef Name=\"FilePath\" /></Key><Property Name=\"Name\" T" +
                "ype=\"Edm.String\" Nullable=\"false\" /><Property Name=\"Publisher\" Type=\"Edm.String\"" +
                " Nullable=\"false\" /><Property Name=\"Version\" Type=\"Edm.String\" Nullable=\"false\" " +
                "/><Property Name=\"FilePath\" Type=\"Edm.String\" Nullable=\"false\" /><Property Name=" +
                "\"ContentType\" Type=\"Edm.String\" /><NavigationProperty Name=\"GalleryItem\" Relatio" +
                "nship=\"MicrosoftCompute.GalleryPackageContentFile_GalleryItem\" ToRole=\"GalleryIt" +
                "em\" FromRole=\"GalleryPackageContentFile\" /></EntityType><EntityType Name=\"ViewDe" +
                "finition\" BaseType=\"MicrosoftCompute.NamedVersionedPublishedEntity\" m:HasStream=" +
                "\"true\" /><Association Name=\"GalleryItem_Content\"><End Type=\"MicrosoftCompute.Gal" +
                "leryPackageContentFile\" Role=\"Content\" Multiplicity=\"*\" /><End Type=\"MicrosoftCo" +
                "mpute.GalleryItem\" Role=\"GalleryItem\" Multiplicity=\"*\" /></Association><Associat" +
                "ion Name=\"GalleryPackageContentFile_GalleryItem\"><End Type=\"MicrosoftCompute.Gal" +
                "leryPackageContentFile\" Role=\"GalleryPackageContentFile\" Multiplicity=\"*\" /><End" +
                " Type=\"MicrosoftCompute.GalleryItem\" Role=\"GalleryItem\" Multiplicity=\"0..1\" /></" +
                "Association><Annotations Target=\"Microsoft.SystemCenter.Foundation.GalleryServic" +
                "e.GalleryDataProvider\"><ValueAnnotation Term=\"Com.Microsoft.Data.Services.Conven" +
                "tions.V1.UrlConventions\" String=\"KeyAsSegment\" /></Annotations></Schema><Schema " +
                "Namespace=\"Microsoft.SystemCenter.Foundation.GalleryService\" xmlns=\"http://schem" +
                "as.microsoft.com/ado/2009/11/edm\"><EntityContainer Name=\"GalleryDataProvider\" m:" +
                "IsDefaultEntityContainer=\"true\"><EntitySet Name=\"GalleryItems\" EntityType=\"Micro" +
                "softCompute.GalleryItem\" /><EntitySet Name=\"GalleryPackageContentFiles\" EntityTy" +
                "pe=\"MicrosoftCompute.GalleryPackageContentFile\" /><EntitySet Name=\"ViewDefinitio" +
                "ns\" EntityType=\"MicrosoftCompute.ViewDefinition\" /><AssociationSet Name=\"Gallery" +
                "Item_Content\" Association=\"MicrosoftCompute.GalleryItem_Content\"><End Role=\"Gall" +
                "eryItem\" EntitySet=\"GalleryItems\" /><End Role=\"Content\" EntitySet=\"GalleryPackag" +
                "eContentFiles\" /></AssociationSet><AssociationSet Name=\"GalleryPackageContentFil" +
                "e_GalleryItem\" Association=\"MicrosoftCompute.GalleryPackageContentFile_GalleryIt" +
                "em\"><End Role=\"GalleryPackageContentFile\" EntitySet=\"GalleryPackageContentFiles\"" +
                " /><End Role=\"GalleryItem\" EntitySet=\"GalleryItems\" /></AssociationSet></EntityC" +
                "ontainer></Schema></edmx:DataServices></edmx:Edmx>";
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static string GetConcatenatedEdmxString()
            {
                return string.Concat(ModelPart0);
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            public static global::Microsoft.Data.Edm.IEdmModel GetInstance()
            {
                return ParsedModel;
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::Microsoft.Data.Edm.IEdmModel LoadModelFromString()
            {
                string edmxToParse = GetConcatenatedEdmxString();
                global::System.Xml.XmlReader reader = CreateXmlReader(edmxToParse);
                try
                {
                    return global::Microsoft.Data.Edm.Csdl.EdmxReader.Parse(reader);
                }
                finally
                {
                    ((global::System.IDisposable)(reader)).Dispose();
                }
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::System.Xml.XmlReader CreateXmlReader(string edmxToParse)
            {
                return global::System.Xml.XmlReader.Create(new global::System.IO.StringReader(edmxToParse));
            }
        }
    }
    /// <summary>
    /// 架构中不存在 MicrosoftCompute.NamedVersionedPublishedEntity 的注释。
    /// </summary>
    /// <KeyProperties>
    /// Name
    /// Publisher
    /// Version
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Name", "Publisher", "Version")]
    public abstract partial class NamedVersionedPublishedEntity : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// 架构中不存在属性 Name 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// 架构中不存在属性 Publisher 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Publisher
        {
            get
            {
                return this._Publisher;
            }
            set
            {
                this.OnPublisherChanging(value);
                this._Publisher = value;
                this.OnPublisherChanged();
                this.OnPropertyChanged("Publisher");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Publisher;
        partial void OnPublisherChanging(string value);
        partial void OnPublisherChanged();
        /// <summary>
        /// 架构中不存在属性 Version 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Version
        {
            get
            {
                return this._Version;
            }
            set
            {
                this.OnVersionChanging(value);
                this._Version = value;
                this.OnVersionChanged();
                this.OnPropertyChanged("Version");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Version;
        partial void OnVersionChanging(string value);
        partial void OnVersionChanged();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// 架构中不存在 MicrosoftCompute.GalleryItem 的注释。
    /// </summary>
    /// <KeyProperties>
    /// Name
    /// Publisher
    /// Version
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("GalleryItems")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Name", "Publisher", "Version")]
    public abstract partial class GalleryItem : NamedVersionedPublishedEntity
    {
        /// <summary>
        /// 架构中不存在属性 ContentUrl 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ContentUrl
        {
            get
            {
                return this._ContentUrl;
            }
            set
            {
                this.OnContentUrlChanging(value);
                this._ContentUrl = value;
                this.OnContentUrlChanged();
                this.OnPropertyChanged("ContentUrl");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ContentUrl;
        partial void OnContentUrlChanging(string value);
        partial void OnContentUrlChanged();
        /// <summary>
        /// 架构中不存在属性 Description 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                this.OnDescriptionChanging(value);
                this._Description = value;
                this.OnDescriptionChanged();
                this.OnPropertyChanged("Description");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Description;
        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();
        /// <summary>
        /// 架构中不存在属性 IconUrl 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string IconUrl
        {
            get
            {
                return this._IconUrl;
            }
            set
            {
                this.OnIconUrlChanging(value);
                this._IconUrl = value;
                this.OnIconUrlChanged();
                this.OnPropertyChanged("IconUrl");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _IconUrl;
        partial void OnIconUrlChanging(string value);
        partial void OnIconUrlChanged();
        /// <summary>
        /// 架构中不存在属性 Label 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Label
        {
            get
            {
                return this._Label;
            }
            set
            {
                this.OnLabelChanging(value);
                this._Label = value;
                this.OnLabelChanged();
                this.OnPropertyChanged("Label");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Label;
        partial void OnLabelChanging(string value);
        partial void OnLabelChanged();
        /// <summary>
        /// 架构中不存在属性 PublishDate 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTime> PublishDate
        {
            get
            {
                return this._PublishDate;
            }
            set
            {
                this.OnPublishDateChanging(value);
                this._PublishDate = value;
                this.OnPublishDateChanged();
                this.OnPropertyChanged("PublishDate");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTime> _PublishDate;
        partial void OnPublishDateChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnPublishDateChanged();
        /// <summary>
        /// 架构中不存在属性 PublisherLabel 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string PublisherLabel
        {
            get
            {
                return this._PublisherLabel;
            }
            set
            {
                this.OnPublisherLabelChanging(value);
                this._PublisherLabel = value;
                this.OnPublisherLabelChanged();
                this.OnPropertyChanged("PublisherLabel");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _PublisherLabel;
        partial void OnPublisherLabelChanging(string value);
        partial void OnPublisherLabelChanged();
        /// <summary>
        /// 架构中不存在 Content 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<GalleryPackageContentFile> Content
        {
            get
            {
                return this._Content;
            }
            set
            {
                this._Content = value;
                this.OnPropertyChanged("Content");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<GalleryPackageContentFile> _Content = new global::System.Data.Services.Client.DataServiceCollection<GalleryPackageContentFile>(null, global::System.Data.Services.Client.TrackingMode.None);
    }
    /// <summary>
    /// 架构中不存在 MicrosoftCompute.ResourceDefinitionGalleryItem 的注释。
    /// </summary>
    /// <KeyProperties>
    /// Name
    /// Publisher
    /// Version
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Name", "Publisher", "Version")]
    public abstract partial class ResourceDefinitionGalleryItem : GalleryItem
    {
        /// <summary>
        /// 架构中不存在属性 ResourceDefinition 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceStreamLink ResourceDefinition
        {
            get
            {
                return this._ResourceDefinition;
            }
            set
            {
                this.OnResourceDefinitionChanging(value);
                this._ResourceDefinition = value;
                this.OnResourceDefinitionChanged();
                this.OnPropertyChanged("ResourceDefinition");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceStreamLink _ResourceDefinition;
        partial void OnResourceDefinitionChanging(global::System.Data.Services.Client.DataServiceStreamLink value);
        partial void OnResourceDefinitionChanged();
        /// <summary>
        /// 架构中不存在属性 ResourceDefinitionUrl 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ResourceDefinitionUrl
        {
            get
            {
                return this._ResourceDefinitionUrl;
            }
            set
            {
                this.OnResourceDefinitionUrlChanging(value);
                this._ResourceDefinitionUrl = value;
                this.OnResourceDefinitionUrlChanged();
                this.OnPropertyChanged("ResourceDefinitionUrl");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ResourceDefinitionUrl;
        partial void OnResourceDefinitionUrlChanging(string value);
        partial void OnResourceDefinitionUrlChanged();
        /// <summary>
        /// 架构中不存在属性 ViewDefinitionUrl 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ViewDefinitionUrl
        {
            get
            {
                return this._ViewDefinitionUrl;
            }
            set
            {
                this.OnViewDefinitionUrlChanging(value);
                this._ViewDefinitionUrl = value;
                this.OnViewDefinitionUrlChanged();
                this.OnPropertyChanged("ViewDefinitionUrl");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ViewDefinitionUrl;
        partial void OnViewDefinitionUrlChanging(string value);
        partial void OnViewDefinitionUrlChanged();
    }
    /// <summary>
    /// 架构中不存在 MicrosoftCompute.VMRoleGalleryItem 的注释。
    /// </summary>
    /// <KeyProperties>
    /// Name
    /// Publisher
    /// Version
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Name", "Publisher", "Version")]
    public partial class VMRoleGalleryItem : ResourceDefinitionGalleryItem
    {
        /// <summary>
        /// 创建新的 VMRoleGalleryItem 对象。
        /// </summary>
        /// <param name="name">Name 的初始值。</param>
        /// <param name="publisher">Publisher 的初始值。</param>
        /// <param name="version">Version 的初始值。</param>
        /// <param name="resourceDefinition">ResourceDefinition 的初始值。</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static VMRoleGalleryItem CreateVMRoleGalleryItem(string name, string publisher, string version, global::System.Data.Services.Client.DataServiceStreamLink resourceDefinition)
        {
            VMRoleGalleryItem vMRoleGalleryItem = new VMRoleGalleryItem();
            vMRoleGalleryItem.Name = name;
            vMRoleGalleryItem.Publisher = publisher;
            vMRoleGalleryItem.Version = version;
            vMRoleGalleryItem.ResourceDefinition = resourceDefinition;
            return vMRoleGalleryItem;
        }
    }
    /// <summary>
    /// 架构中不存在 MicrosoftCompute.GalleryPackageContentFile 的注释。
    /// </summary>
    /// <KeyProperties>
    /// Name
    /// Publisher
    /// Version
    /// FilePath
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("GalleryPackageContentFiles")]
    [global::System.Data.Services.Common.HasStreamAttribute()]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Name", "Publisher", "Version", "FilePath")]
    public partial class GalleryPackageContentFile : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// 创建新的 GalleryPackageContentFile 对象。
        /// </summary>
        /// <param name="name">Name 的初始值。</param>
        /// <param name="publisher">Publisher 的初始值。</param>
        /// <param name="version">Version 的初始值。</param>
        /// <param name="filePath">FilePath 的初始值。</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static GalleryPackageContentFile CreateGalleryPackageContentFile(string name, string publisher, string version, string filePath)
        {
            GalleryPackageContentFile galleryPackageContentFile = new GalleryPackageContentFile();
            galleryPackageContentFile.Name = name;
            galleryPackageContentFile.Publisher = publisher;
            galleryPackageContentFile.Version = version;
            galleryPackageContentFile.FilePath = filePath;
            return galleryPackageContentFile;
        }
        /// <summary>
        /// 架构中不存在属性 Name 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// 架构中不存在属性 Publisher 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Publisher
        {
            get
            {
                return this._Publisher;
            }
            set
            {
                this.OnPublisherChanging(value);
                this._Publisher = value;
                this.OnPublisherChanged();
                this.OnPropertyChanged("Publisher");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Publisher;
        partial void OnPublisherChanging(string value);
        partial void OnPublisherChanged();
        /// <summary>
        /// 架构中不存在属性 Version 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Version
        {
            get
            {
                return this._Version;
            }
            set
            {
                this.OnVersionChanging(value);
                this._Version = value;
                this.OnVersionChanged();
                this.OnPropertyChanged("Version");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Version;
        partial void OnVersionChanging(string value);
        partial void OnVersionChanged();
        /// <summary>
        /// 架构中不存在属性 FilePath 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string FilePath
        {
            get
            {
                return this._FilePath;
            }
            set
            {
                this.OnFilePathChanging(value);
                this._FilePath = value;
                this.OnFilePathChanged();
                this.OnPropertyChanged("FilePath");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _FilePath;
        partial void OnFilePathChanging(string value);
        partial void OnFilePathChanged();
        /// <summary>
        /// 架构中不存在属性 ContentType 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string ContentType
        {
            get
            {
                return this._ContentType;
            }
            set
            {
                this.OnContentTypeChanging(value);
                this._ContentType = value;
                this.OnContentTypeChanged();
                this.OnPropertyChanged("ContentType");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _ContentType;
        partial void OnContentTypeChanging(string value);
        partial void OnContentTypeChanged();
        /// <summary>
        /// 架构中不存在 GalleryItem 的注释。
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public GalleryItem GalleryItem
        {
            get
            {
                return this._GalleryItem;
            }
            set
            {
                this._GalleryItem = value;
                this.OnPropertyChanged("GalleryItem");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private GalleryItem _GalleryItem;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// 架构中不存在 MicrosoftCompute.ViewDefinition 的注释。
    /// </summary>
    /// <KeyProperties>
    /// Name
    /// Publisher
    /// Version
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("ViewDefinitions")]
    [global::System.Data.Services.Common.HasStreamAttribute()]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Name", "Publisher", "Version")]
    public partial class ViewDefinition : NamedVersionedPublishedEntity
    {
        /// <summary>
        /// 创建新的 ViewDefinition 对象。
        /// </summary>
        /// <param name="name">Name 的初始值。</param>
        /// <param name="publisher">Publisher 的初始值。</param>
        /// <param name="version">Version 的初始值。</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static ViewDefinition CreateViewDefinition(string name, string publisher, string version)
        {
            ViewDefinition viewDefinition = new ViewDefinition();
            viewDefinition.Name = name;
            viewDefinition.Publisher = publisher;
            viewDefinition.Version = version;
            return viewDefinition;
        }
    }
}
